""" Rack command line argument generator

Utility for constructing strings that can be executed in shell.

    * property
    * property2

"""
import argparse
from ctypes.wintypes import SIZE
from html import parser
import sys
from pathlib import Path
import os
import re # GEOCONF filename-KEY extraction
import inspect
import logging

from types import SimpleNamespace

from matplotlib import lines, scale
from numpy import size
from sympy import arg

from rack import script
import rack.log
import rack.prog
import rack.cmdline
import rack.gnuplot
import rack.core
import rack.args
import rack.vertical
#from rack.vertical import (
#    read_default_args, export_defaults_to_json,
#    handle_infile, handle_style,
#)


logger = rack.log.logger.getChild(Path(__file__).stem)
# logger.setLevel(logging.INFO)

reg = rack.prog.Register



def build_parser():
    """ Creates registry of supported options of this script
    """
    parser = argparse.ArgumentParser(description="Pseudo-RHI generator")

    # Rhi specific parameters
    
    rack.prog.Register.expand_options(
        rack.core.Rack.pPseudoRhi, 
        parser, 
        name_mapper=True) # rack.prog.camel_to_upper_underscore)
    
    parser.add_argument(
        "--background",   
        metavar="<intensity>|<red,green,blue>",
        default="0", # black
        help="Illustrate radar beams with given background color.")

    rack.prog.Register.expand_options(
        rack.core.Rack.select, 
        parser, 
        name_mapper=True) 
    #rack.prog.camel_to_upper_underscore)     

    rack.vertical.complete_arg_parser(parser)

    parser.add_argument(
        "--STYLE",
        default=".RAY=stroke:white;stroke-width:3;stroke-linecap:round;",
        help="Adjust CSS styles for the SVG output")

    return parser





def handle_outfiles_prhi(args, cmdBuilder: rack.core.Rack) -> str:
    """
        Handle output file naming and formats for the Pseudo-RHI product.
        This includes:
        - Setting the output file for the Pseudo-RHI image (e.g. SVG)
        - Handling auxiliary outputs (e.g. HDF5) if specified in args.FORMAT
        - Setting up the GnuPlot output file for the Pseudo-RHI image, 
        which may be used as background for the main SVG output.
    """

    if 'h5' in args.FORMAT:
        cmdBuilder.outputFile(f"{args.basename}.h5")
        args.FORMAT.remove('h5')

    cmdBuilder.paletteDefault()

    # print(args)
    # anticipated gnuplot-produced image:
    #SIZE = str(args.size).replace(':', ',').split(',')
    SIZE = rack.typical(args.size, tuple, ':')
    logger.warning(f"Parsed size: {SIZE}")
    cmdBuilder.cSize(SIZE[0], SIZE[1])
    # Linking wants full path.
    cmdBuilder.gLinkImage(f"{args.OUTDIR}{args.gnuplot}")
    
    if args.background  != "":  # color
        cmdBuilder.select(quantity='QIND')
        cmdBuilder.encoding(type="C", gain=0.004, offset=0) # 
        cmdBuilder.imageAlpha()
        cmdBuilder.imageFlatten(args.background)

    # This is for gnuplot script to use as background
    cmdBuilder.gInclude("SKIP")
    cmdBuilder.outputFile(f"{args.basename}-background.png")
    




def handle_vert_product(args, progBuilder: rack.core.Rack):
    # range is already in metres; pass directly to gRadarSector
    progBuilder.gRadarRay(radius=args.range.replace(',', ':'), azimuth=args.az_angle)


def handle_gnuplot(args, progBuilder: rack.core.Rack): #, **kw_args): #range_m:tuple=None, height_m:tuple=None):
    
    if not args.gnuplot:
        return
    
    terminal = args.gnuplot.split('.').pop()
    if terminal not in ['png', 'svg', 'tif']:
        logger.warning(f"Unsupported gnuplot terminal format: {terminal}, defaulting to png")
        terminal = 'png'

    gpl_plot = rack.prog.CommandSequence()
    gpl_plot.fmt = rack.gnuplot.GnuPlotFormatter(param_separator=',\n  ')
    gpl_plot.fmt.cmd_separator='\n'
    gpl_plot.fmt.CMD_SEPARATOR='\n'

    confCmdReg = rack.gnuplot.Registry(gpl_plot)
    plotCmdReg = rack.gnuplot.Registry(gpl_plot)
    
    # conf.comment("Generated by rack with --gnuplot option")
    # conf.comment("General settings")
    confCmdReg.terminal(rack.gnuplot.Terminal(terminal), size=args.size) # Hard-coded. See also handle_prhi for size handling.
    confCmdReg.output(args.gnuplot)

    confCmdReg.multiplot()    # (rows=1, cols=1)
    if args.title:
        confCmdReg.title(args.title)
    elif args.select:
        confCmdReg.title(f"Pseudo-RHI [{args.select}] {args.az_angle} deg")
    elif args.title is None:
        confCmdReg.title(f"Pseudo-RHI {args.az_angle} deg")


    confCmdReg.unset("tics")
    confCmdReg.grid(rack.gnuplot.Tics.XTICS, rack.gnuplot.Tics.YTICS)
    confCmdReg.unset("border")

    # consider single command with multiple parameters for margins, e.g. margin left 10, right 20, top 30, bottom 40
    """
    confCmdReg.comment("lmargin at screen 0.22")
    confCmdReg.comment("rmargin at screen 0.9")
    confCmdReg.comment("bmargin at screen 0.18")
    confCmdReg.comment("tmargin at screen 0.9")
    """
    
    # left, right, bottom, top in character units. See also margin command for more flexible margins in screen units.
    confCmdReg.set("margins 12, 4, 4, 3"  ) 

    # confCmdReg.comment("General settings")
    
    plotCmdReg.comment("Plotting the background image (radar beams)")
    #plotCmdReg.plot(filename=get_background_filename(args, prefixed=True), filetype="png", 
    plotCmdReg.plot(filename=f"{args.basename}-background.png", filetype="png",     
                    style=rack.gnuplot.Style.RGBIMAGE) # linecolor='rgb "gray"', linewidth=1)
    
    range_args = {
        "xrange": args.range,
        "yrange": args.height
    }
    for (k,v) in range_args.items():
        if type(v) == list:
            v = tuple(v)
        elif type(v) == str:
            v = tuple(int(i) for i in str(v).strip().split(':'))
        range_args[k] = v

    
    xrange = tuple(range_args.get('xrange', (-250000, 250000)))
    yrange = tuple(range_args.get('yrange', (0, 8000)))

    confCmdReg.xrange(xrange)
    confCmdReg.yrange(yrange)

    # See above unset border, to remove default border and tics,
    # and then add custom border back with margins
    confCmdReg.set("border") 
    confCmdReg.set("tics out nomirror scale 2")
    confCmdReg.set("mxtics 5")
    # confCmdReg.key(rack.gnuplot.Key.LEFT, outside=True)
    confCmdReg.xlabel(f'Range {xrange[0]} – {xrange[1]} m')
    confCmdReg.ylabel(f'Altitude {yrange[0]} – {yrange[1]} m')
    # script.extend(gpl_conf.to_list())
    confCmdReg.unset("key") # legend 

    plotCmdReg.comment("Plotting a dummy line (to ensure gnuplot output is not empty)")
    plotCmdReg.plot('x*0', style=rack.gnuplot.Style.LINES) # linecolor='rgb "gray"', linewidth=1)
    
    script = gpl_plot.to_string()  #"\n".join(script)
    if args.print:
        logger.info("# GnuPlot script:")
        print(script)
    
    # Always write the GnuPlot script to a file, even if not executing it,
    # for debugging and user reference. The filename is derived from the --gnuplot argument.
    if not args.gnuplot_script:
        args.gnuplot_script = f"{args.gnuplot}.gnu" 
    #args.gnuplot_script = get_background_filename(args, prefixed=False).removesuffix(f".{terminal}") + ".gnu"
    #script_filename = f"{args.gnuplot}.gnu" # TODO replace .png -> -png.gnu, .svg -> -svg.gnu, etc.
    with open(args.gnuplot_script, "w") as f:
        f.write(script)
        logger.info(f"GnuPlot script written to: {args.gnuplot_script}")
    
    return script


def compose_command(args) -> rack.prog.CommandSequence:
    """ Standard entry point.

    For example, test programs expect compose_command() as the interface for generating the command sequence to be tested,
    and exec_command() is the interface for executing the generated command sequence. 

    Args:
        args (argparse.Namespace): Parsed arguments from `build_parser()`
    """

    global logger

    if isinstance(args, dict):
        args = argparse.Namespace(**args)

    #logger.info(f"Parsed args: {args}")

    # Rack command sequence, the "program" to be executed
    rackProg = rack.prog.CommandSequence(programName='rack', quote="'")

    # consider also PythonCommandSequence 

    # Command registry, "factory" for adding command to the program sequence.
    rackCmdReg = rack.core.Rack(rackProg)

    # Vertical product common commands (e.g. radar sector, radar ray)
    rack.vertical.initialize_rack(args, rackCmdReg)
    
    # Pseudo-RHI specific commands:
    handle_vert_product(args, rackCmdReg)
    rackCmdReg.handle_published_cmd_args(args, rack.core.Rack.select)
    rackCmdReg.handle_published_cmd_args(args, rack.core.Rack.pPseudoRhi, True)
    handle_outfiles_prhi(args, rackCmdReg)
    handle_gnuplot(args, rackCmdReg)

    rack.vertical.finalize_svg_output(args, rackCmdReg)
    #if 'svg' in args.FORMAT:
    #    rackCmdReg.outputFile(f"{args.basename}.svg")
    #    args.FORMAT.remove('svg')

    if 'tif' in args.FORMAT:
        #cmdBuilder.outputConf("tif:tile=512")
        #cmdBuilder.outputFile(f"{args.basename}.tif")
        logger.warning("TIFF output is not currently supported, skipping.")
        args.FORMAT.remove('tif')

    if args.FORMAT:
        raise Exception('Unhandled formats:', args.FORMAT)
    
    return rackProg


    
def main():
    rack.vertical.run_module(sys.modules[__name__])


if __name__ == "__main__":
    main()
