{
  {"title", "CLASS"},
  {"nodata", {"Class indices (~thresholds) are also quality index values 0...255.", "nodata", {255.0,255.0,255.0}} },
  {"undetect", {"undetect", {0.0,0.0,0.0}} },
  {       5.0, {"error", "Error", {192.0,192.0,192.0}} },
  {     128.0, {"weak", "Weak top", {0.0,128.0,224.0}} },
  {     170.0, {"interpolated", "Interpolated", {64.0,192.0,64.0}} },
  {     200.0, {"interpolated.undetect", "Dry top, interpolated", {240.0,180.0,0.0}} },
  {     240.0, {"extrapolated.dry", "Strong top, extrapolated", {255.0,64.0,0.0}} }
}
