{
  {"title", "CLASS"},
  {"nodata", {"Class indices (~thresholds) are also quality index values 0...255.", "nodata", {255,255,255}} },
  {"undetect", {"undetect", {0,0,0}} },
  {         5, {"error", "Error", {192,192,192}} },
  {       128, {"weak", "Weak top", {0,128,224}} },
  {       170, {"interpolated", "Interpolated", {64,192,64}} },
  {       200, {"interpolated.undetect", "Dry top, interpolated", {240,180,0}} },
  {       240, {"strong.extrapolated", "Strong top, extrapolated", {255,64,0}} }
}
