{
  {"title", "CLASS"},
  {"nodata", {"Class indices (~thresholds) are also quality index values 0...255.", "nodata", {255,255,255}} },
  {"undetect", {"undetect", {0,0,0}} },
  {         5, {"error", "Error", {192,192,192}} },
  {       128, {"weak", "Constrained MaxH", {0,128,224}} },
  {       170, {"interpolated", "Well-defined", {64,192,64}} },
  {       200, {"interpolated.undetect", "Constrained span", {240,180,0}} },
  {       240, {"strong.extrapolated", "Constrained MinH", {255,64,0}} }
}
