{
  {"title", "CLASS"},
  {"nodata", {"Class indices (~thresholds) are also quality index values 0...255.", "nodata", {255.0,255.0,255.0}} },
  {"undetect", {"undetect", {0.0,0.0,0.0}} },
  {       5.0, {"error", "Error", {255.0,64.0,0.0}} },
  {     128.0, {"weak", "Weak top (below threshold)", {255.0,255.0,0.0}} },
  {     170.0, {"extrapolated.dry", "Strong top, extrapolated", {0.0,192.0,240.0}} },
  {     200.0, {"interpolated.undetect", "Interpolated, dry top", {0.0,240.0,192.0}} },
  {     240.0, {"interpolated", "Interpolated", {64.0,255.0,64.0}} }
}
