
# Install environment & dependencies for rack

FROM ubuntu:18.04
RUN apt-get update 

# Install libraries (runtime versions only)
# Found using queries like: apt search libpng runtime
RUN apt-get -y install libhdf5-100 libproj12 libpng16-16 libtiff5 libgeotiff2 libgomp1

COPY bin/rack /usr/local/bin

# Consider:
# libgeotiff-epsg/bionic 1.4.2-1 all
# GeoTIFF library -- EPSG Geodetic Parameter Dataset

WORKDIR rack

CMD ["rack","--version"]
