# proj=' +proj=aeqd +lon_0=23.0764 +lat_0=61.7673 +ellps=WGS84'
# BBOX='18.6913,59.4489 28.1476,63.9227'
# XRANGE='18.6913:28.1476'
# YRANGE='59.4489:63.9227'
# size='500x500'
# iStep=30
# jStep=30
# sampleRows=16
# sampleCols=16
# samples=256
# format='{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}'
{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}
{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}
{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}
{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}
{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}
...
	...
		...
{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}
{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}
{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}
{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}
{i},{j},{LON},{LAT},{X},{Y},{j2},{AMVU},{AMVV},{QIND}
