{
	// See drain/examples/ImageCodeMap-example.cpp
	{324.123, {"värinen", {1.1, 14.0, 33.0}, 0.5}},
	{314.123, {"toinen", {1.1, 14.0, 33.0}, 0.5}}
	/*
	 { //
	// colour entries
    {10, "tech.err.time", "Timing problem", {240,240,240} },
    {13, "tech.class.unclass", "Unclassified", {144,144,144} },
    {14.123, "toinen", {1.1,14,33,0.5}, 0.5 },
    {24.123, "värinen", {1.1,14,33,0.5}, 0.5 },
    {64, "precip", "Precipitation", {80,208,80} },
    {72, "precip.widespread", "Rain", {32,248,96} },
    {80, "precip.snow", "Snow", {0,208,255} },
    {104, "precip.conv.graupel", "Graupel", {176,0,255} },
    {112, "precip.conv.hail", "Hail", {224,128,255} },
    {128, "nonmet", "Non-meteorological", {255,192,0} },
    {144, "nonmet.clutter", "Clutter", {180,96,0} },
    {148, "nonmet.clutter.ground", "Ground clutter", {160,92,64} },
    {152, "nonmet.clutter.sea", "Sea clutter", {128,128,160} },
    {166, "nonmet.artef.vessel.ship", "Ship", {170,208,255} },
    {176, "nonmet.biol", "Organic target", {255,64,64} },
    {180, "nonmet.biol.insect", "Insects", {255,248,0} },
    {184, "nonmet.biol.bird", "Birds", {255,0,128} },
    {196, "dist.attn.rain", "Attenuation in rain", {255,224,224} },
    {232, "signal.noise", "Receiver noise", {240,240,240} },
    {240, "signal.emitter", "External emitter", {240,240,128} },
    {242, "signal.emitter.line", "Emitter line or segment", {240,208,224} },
    {246, "signal.emitter.jamming", "Jamming", {240,224,208} },
    {248, "signal.sun", "Sun", {255,255,192} }
}

	 */
}
